- id: 1
  key: satoshi
  code: btc
  symbol: "à¸¿"
  coin: true
  quick_withdraw_max: 0
  rpc: http://username:password@127.0.0.1:18332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3
- id: 2
  key: ether
  code: eth
  symbol: "E"
  coin: true
  precision: 4
  quick_withdraw_max: 0
  rpc: http://Your_eth_server_ip
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/address/#{address}
  assets:
    accounts:
      -
        address: 0x4bA2474e063Aec44e23F2Bf7Fb9e4e2878dBaB44